spring:
  application:
    name: lap-tracker-service

  datasource:
    url: jdbc:postgresql://localhost:5432/lap_tracker
    username: ${DB_USERNAME:lap_tracker_user}
    password: ${DB_PASSWORD:lap_tracker_pass}
    driver-class-name: org.postgresql.Driver
    
    # HikariCP Connection Pool Settings
    hikari:
      pool-name: LapTrackerHikariPool
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000          # 5 minutes
      max-lifetime: 1200000         # 20 minutes
      connection-timeout: 20000     # 20 seconds
      leak-detection-threshold: 60000  # 1 minute (for debugging)

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    
    properties:
      hibernate:
        connection:
        generate_statistics: false

        format_sql: false
        use_sql_comments: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: '0'

# logging
logging:
  level:
    root: INFO
    com.laptracker: INFO
    # org.hibernate.SQL: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE
    # org.hibernate.engine.jdbc.batch: DEBUG
    com.zaxxer.hikari: INFO
    org.springframework.data.jpa: INFO

# observation tools setup
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.90, 0.95, 0.99

server:
  port: 8080
  shutdown: graceful